server:
  port: 7007
  servlet:
    session:
      timeout: 1h
  compression:
    enabled: true
    min-response-size: 1024
spring:
  h2:
    console:
      enabled: true
  datasource:
    username: sa
    password: sa
    url: jdbc:h2:tcp://localhost/~/survey
    driver-class-name: org.h2.Driver
mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
    call-setters-on-nulls: false
  global-config:
    db-config:
      logic-delete-field: deleted
#      update-strategy: not_null # 对于 null 的字段，不给更新为空
file-storage:
  local:
    root-path: /Users/dahuang/Downloads/files
custom-cache:
  entries:
    fileCache: 1h
